### ISSUE TITLE
Move repo so that RAISE lab has access

### ISSUE THREAD

**Issue by timm** [yrahul3910/raise#26]

**Comment by yrahul3910** [comment]
This repo is open for PRs! 

I don't have push access to the `ai-se` org, so I can't do it myself, but you could also set up a mirror through GitHub Actions, see [Mirror docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository):

```yaml
name: Mirror Repository

on:
  schedule:
    - cron: '@weekly'
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the original repository
        uses: actions/checkout@v2
        with:
          repository: yrahul3910/raise
          token: ${{ secrets.GITHUB_TOKEN }} 
          fetch-depth: 0
      
      - name: Push to the mirror repository
        run: |
          git remote add mirror https://github.com/ai-se/raise_utils.git
          git push --mirror mirror
```
